---
- :key_path: "./secret.key"
- :password:
    :value: |-
      ?pEghAtKW3DozfXWGo0dsxEs4Wlo/vsD13TkMUQazvIVroq+V+yamcrEmAqMe
      upsT
    :desc: This Value is Encrypt Sample
  :"e-mail":
    :value: |-
      ?LdQNSP9i6CuczTXsIC2ixSOLLi0TQW73n43zIyiL+435HfRGeYQS1jz8ZBJv
      y4AgU4f2ZWtvegZZrhJpAu6kUh6LAwz2XfsxOV77EorukDQ=
    :desc: Override Value
